### PR TITLE
Major improvements in site performance and design.

### PR DESCRIPTION
**Pull request by Smarticles101**

### CODE REVIEW

**Comment by Reetik2000** [comment]
no

**Comment by Smarticles101** [comment]
Why not

**Comment by Reetik2000** [comment]
go mess up someone else's repos logan

**Comment by Smarticles101** [comment]
https://github.com/crdnl/new-acronyms/issues/1

I'm already trying

**Comment by Smarticles101** [comment]
I'm also actually contributing to some stuff though

**Pull request closed without merging**
